### ISSUE TITLE
jest reports that cacheable-lookup is leaking

### ISSUE THREAD

**Issue by kirillgroshkov** [szmarczak/cacheable-lookup#19] opened 2020-04-28 18:28 UTC
This is not my best issue report, since ATM I don't have time to put up the proper minimal repro.

But, when running `jest --detectLeaks --detectOpenHandles` (I guess only `--detectOpenHandles` is relevant here) it often prints this:

```
Test Suites: 1 failed, 11 passed, 12 total
Tests:       1 todo, 17 passed, 18 total
Snapshots:   0 total
Time:        10.615s

Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  DNSCHANNEL

    > 1 | import got from 'got'
        | ^
      2 | 
      3 | const detectLeaks = process.argv.some(a => a.includes('detectLeaks'))
      4 | 

      at new CacheableLookup (node_modules/cacheable-lookup/source/index.js:62:14)
      at Object.<anonymous> (node_modules/got/dist/source/index.js:60:19)
      at Object.<anonymous> (src/jestOffline.util.test.ts:1:1)
```

I'll just leave this issue there until I have more information, or someone else comes with a better reproduction..

`got@11` is used here

**Comment by szmarczak** [comment] 2020-04-28 19:54
Duplicate of https://github.com/sindresorhus/got/issues/1196

```js                          
const got = require('got');

/*test('test',*/ (async () => {
  const data = await got('https://www.google.com');

//  expect(typeof data).toBe('object');
//  data.destroy(); // The same problem occurs without this code.
})();
```

If you run this code you can clearly see that the process exits. So it's not Got's neither CacheableLookup's fault. @CatsMiaow already [made a comment](https://github.com/facebook/jest/issues/6423#issuecomment-620407580) on Jest repo with simplest reproducible code.

**Closed by szmarczak** 2020-04-28 19:54 UTC
